apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  pg_hba_conf: |
    local   all             all                                     trust
    local   replication     all                                     trust
    host all all all md5
  install_pg_hba_conf: |
    #!/bin/sh

    cp /tmp/pg_hba.conf /var/lib/postgresql/data/pg_hba.conf
